Adjusting directory organization with new proposed standard
finos/cloud-service-certification pull request #102
Opened 2021-03-02 16:15 UTC by eddie-knight

2021-03-02 16:23 UTC, mcleo-d commented on docs/directory-structure.md
> +The CSC repository contains three types of content: Service Accellerator Templates, Infrastructure as Code, and Automated Testing.
Typo : `Accellerator` should be `Accelerator`

2021-03-02 16:23 UTC, mcleo-d commented on docs/directory-structure.md
> +## Service Accellerator Templates
Typo : `Accellerator` should be `Accelerator`

2021-03-02 16:24 UTC, mcleo-d commented on docs/directory-structure.md
> +1. `service_accellerator_templates/`
Typo : `Accellerator` should be `Accelerator`

2021-03-02 16:24 UTC, mcleo-d commented on docs/directory-structure.md
> +`aws/service_accellerator_templates/dynamodb`
Typo : `Accellerator` should be `Accelerator`

2021-03-02 16:25 UTC, mcleo-d commented on docs/directory-structure.md
> +            # Service Accellerator Templates
Typo : `Accellerator` should be `Accelerator`

2021-03-02 16:26 UTC, mcleo-d commented on docs/directory-structure.md
> +    service_accellerator_templates/
Typo : `service_accellerator_templates/` should be `service_accelerator_templates/`

2021-03-02 16:26 UTC, mcleo-d commented on docs/directory-structure.md
> +            # Service Accellerator Templates
Typo : `Accellerator` should be `Accelerator`

2021-03-02 16:27 UTC, mcleo-d commented on docs/directory-structure.md
> +Terraform contributions should always take advantage of [modules](https://www.terraform.io/docs/language/modules/develop/index.html). Modules should live in `<CSP>/terraform/modules`. Containing all
Typo: `unecessary` should be `unnecessary`

2021-03-02 16:31 UTC, mcleo-d commented
Hi @eddie-knight

Thanks so much for the PR 🚀  

I have taken a brief read through of `docs/directory-structure.md` and found a few minor typos that I've highlighted in the commit.

I've also noticed the FINOS CLABot has been triggered. I'll email you directly regarding this issue.

Thanks once again! 😁 

James.

2021-03-04 15:27 UTC, mcleo-d commented
Hi @eddie-knight

I have assigned this PR to @peterrhysthomas for review and will add to the next CSC meeting for you to introduce to the group. 

Also, please refer to the following comment regarding the CLABot warning ... https://github.com/finos/cloud-service-certification/pull/104#issuecomment-790697916

Speak soon,

James.

2021-04-05 19:13 UTC, eddie-knight commented
Per previous conversations, I've modified this PR to simply state the expectations within the contribution docs.

If this is agreeable, we can follow up with additional PRs that adjust the existing contributions to meet the standard outlined here.

2021-04-06 13:47 UTC, mcleo-d commented
Hi @eddie-knight,

Thanks for the comment below. Feel free to add a link to this PR in the comments of https://github.com/finos/cloud-service-certification/issues/112 to make sure we discuss with @peterrhysthomas / @abdullahgarcia and agree a way forward at this weeks mid sprint session.

Keep safe and speak soon 🤘😆 

James.

> Per previous conversations, I've modified this PR to simply state the expectations within the contribution docs.
> 
> If this is agreeable, we can follow up with additional PRs that adjust the existing contributions to meet the standard outlined here.

2021-04-21 13:10 UTC, abdullahgarcia requested changes
@eddie-knight , can we please look over the proposed directory structure? 

I'm currently concerned about how we handle the services for each cloud service provider.

We currently hold a sub-directory for each service to ensure it is easy to navigate and keep segregation for the files involved. 

That isn't depicted in the current structure.

Please let me know how we can address this matter.

2021-04-22 01:06 UTC, eddie-knight commented
I'd love to discuss and apply any suggestions. Should we discuss this on the call tomorrow or do you want to propose an improvement here via the comments?

2021-04-22 08:44 UTC, abdullahgarcia commented
Let's see how the session goes tomorrow. If there's time, we can discuss it and perhaps gain everyone else's feedback too. Otherwise, we can set something up.

2021-04-28 16:45 UTC, eddie-knight commented on .github/CONTRIBUTING.md
> +# finos/cloud-services-certification
Added these changes in my previous commit

2021-04-28 16:46 UTC, eddie-knight commented on .github/CONTRIBUTING.md
> +# finos/cloud-services-certification
changes applied in commit d416596

2021-05-23 20:47 UTC, abdullahgarcia approved these changes
As per the last CSC call, all looks good.

2021-05-24 07:41 UTC, peterrhysthomas approved these changes

2021-05-24 07:41 UTC, merged

2021-05-27 10:09 UTC, mcleo-d commented
Congratulations on the merge @eddie-knight and @peterrhysthomas 🕺🏻 💃🏻  🎸 🎵 🎶 🎵 🎶 🎵 🎶