Add Cloud Service Certification Project Operations Manager Role
finos/cloud-service-certification pull request #99
Opened 2021-02-15 16:59 UTC by mcleo-d

## Description
This pull request adds the following **Project Operations Manager** role to the Cloud Service Certification `open-roles` folder ...

# Project Operations Manager - Cloud Service Certification 
Helping run [Cloud Service Certification](https://github.com/finos/cloud-service-certification) as Project Operations Manager is a fun open source role involving a broad set of tasks that need to be taken care of, including ... 

## Role Requirements

- Capturing, writing and updating work items as [GitHub Issues](https://github.com/finos/cloud-service-certification/issues).
- Updating and running the [Cloud Service Certification Project Kanban](https://github.com/orgs/finos/projects/1).
- Scheduling [Cloud Service Certification Project Meetings](https://github.com/finos/cloud-service-certification/issues?q=label%3Ameeting+).
- Creating and circulating agendas. 
- Communicating with the project team.
- Updating the [FINOS Community](https://github.com/finos/community/issues).
- Capturing and circulating meeting minutes. 

The Cloud Service Certification Project Operations Manager does not necessarily have to be technical, or a subject matter expert, but should have ...

## Skills Requirements

- Strong organization skills.
- Attention to detail.
- Curiosity and proactiveness.
- Willingness to have fun growing Cloud Service Certification.

The Project Operations Manager will need to be (or become) ... 

- Comfortable using GitHub.
- Comfortable coordinating meetings using WebEx. 

The Project Operations Manager will have to understand the [FINOS Landscape](https://landscape.finos.org), [Open Developer Platform](https://github.com/finos/open-developer-platform) and [FINOS Governance and Policies](https://github.com/finos/community/tree/master/governance). 

The Project Operations Manager works closely with the Cloud Service Certification Lead Maintainer and ensures the project team can collaborate smoothly. The Project Operations Manager will reach out to FINOS for assistance and support as they need it.

## Contact Cloud Service Certification

Contact [James McLeod](james@finos.org), FINOS Director of Community, or  [Peter Thomas](peter.thomas@db.com), Cloud Service Certification Lead Maintainer from Deutsche Bank, for more information or drop into the next [Cloud Service Certification Project Meeting](https://github.com/finos/cloud-service-certification/issues?q=label%3Ameeting+) to say hello.

🌤 🚀 🤖

2021-03-10 08:14 UTC, peterrhysthomas approved these changes

2021-03-10 09:15 UTC, abdullahgarcia requested changes
@mcleo-d all good, just the same issue with the ".DS_Store" files.

2021-03-10 14:27 UTC, mcleo-d commented
Hi @abdullahgarcia 

The following commits remove `.DS_Store` and add `.DS_Store` to `.gitignore` as per https://github.com/finos/cloud-service-certification/pull/103#issuecomment-795464459.

1. remove .DS_Store c14fc32
2. add global .DS_Store to .gitignore 19bf97b

Please let me know if there are merge conflicts.

James.

2021-03-11 10:35 UTC, mcleo-d commented
@peter-thomas-db and @abdullahgarcia 

I have merged this PR based on @abdullahgarcia's feedback being resolved here ... https://github.com/finos/cloud-service-certification/pull/99#issuecomment-795491304

Kind regards,

James.

2021-03-11 10:35 UTC, merged